config/routes.rb
Todos::Application.routes.draw do
  get "welcome/log"
  get 'welcome/index'
  devise_for :users
  resources :todos do
    member do
      post :toggle
    end

    collection do
      post :toggle_all
      get :active
      get :completed
      delete :destroy_completed
    end
  end


  get '/check', to: 'todos#check_password_for'
  root :to => 'welcome#index'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
	belongs_to :user
	after_initialize :init
	def init
		self.completed = false
	end
	attr_accessor :completed
	validates :title, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
#         :token_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#  acts_as_token_authentication_handler_for User
  # Prevent CSRF attacks by raising an exception.
  protect_from_forgery with: :exception
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, :if => Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_filter :authenticate_user!
  def daily_mail
	  DailyMailer.dailysend
  end

  def handle_unverified_request
	raise(ActionController::InvalidAuthenticityToken)
  end
  def index
    @todos = Todo.where('user_id = ?', current_user.id).order(updated_at: :desc)
    respond_to do |format|
	    format.json { render :json => @todos }
	    format.atom
	    format.html
    end
  end

  def todo_params
	  params.require(:todo).permit(:title, :user_id)
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    @todo.completed = false
    @todo.save
    redirect_to 'index'
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
  end

  def show
	  @todo = Todo.where('user_id = ?', current_user.id)
	  respond_to do |format|
		  format.html
		  format.json { render :json => @todo }
	  end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
  end

  def toggle
    @todo = Todo.find(params[:id])
    @todo.toggle!(:completed)
  end

  def toggle_all
    @todos = Todo.where('user_id = ?', current_user.id)
    @todos.each do |t|
      t.toggle!(:completed)
    end
  end

private

  def todo_params
    params.require(:todo).permit(:title, :completed)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	after_filter :set_csrf_header, only: [:new, :create]

	protected

	def set_csrf_header
		   response.headers['X-CSRF-Token'] = form_authenticity_token || nil
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # def new
  #   super
  # end

  def create
    respond_to do |format|
      format.json {
        if !params[:api_key].blank? and params[:api_key] == API_KEY
          build_resource
          if resource.save
            sign_in(resource)
            resource.reset_authentication_token!
            render :template => '/devise/registrations/signed_up' #rabl template with authentication token
          else
            render :template => '/devise/registrations/new' #rabl template with errors
          end
        else
          render :json => {'errors'=>{'api_key' => 'Invalid'}}.to_json, :status => 401
        end
      }
      format.any{super}
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/welcome_controller.rb
require 'csv'
class WelcomeController < ApplicationController
  def log
    CSV.foreach('log/development.log', {:row_sep => '\r\n\r\n'}) do |line|
      puts line.inspect
    end

  end
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def todos_filter_class
    "filtered " + current_filter.to_s
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Task Trackr</title>
	<!-- bootstrap requires JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
	
	<!-- Optional theme -->
	<link rel="stylesheet"
		  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
	
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
  </head>
  
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top"
		role="navigation" style="display:none">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Task Trackr</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>Track your tasks</h1>
        <p class="lead">Project Tracking, grocery lists, we got it all</p>
        <% if notice %>
        <p class="alert alert-success">
		  <%= notice %>
		</p>
        <% end %>
        <% if alert %>
        <p class="alert alert-danger">
		  <%= alert %>
		</p>
		<% end %>
		
		<%= yield %>
		
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug 
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
-->
  </body>
</html>

app/views/layouts/todos.js.erb
<%= yield %>

$("#todoapp").toggleClass("has_todos", <%= Todo.count > 0 %>);

$("#footer").replaceWith("<%= j(render("footer")) %>");

app/views/todos/_destroy.js.erb
$("#<%= dom_id(todo) %>").remove();

app/views/todos/_footer.html.erb
<footer id="footer">
  <span id="todo-count"><strong><%= Todo.where("user_id = #{current_user.id}").count%></strong> <%= "item".pluralize(Todo.count) %> left</span>

  <ul id="filters">
    <li>
      <%= link_to "All", todos_path, class: "all" %>
    </li>
    <li>
  </ul>

</footer>

app/views/todos/_todo.html.erb
<li class="completed" id="<%= dom_id(todo) %>">
    <label data-behavior="todo_title"><%= todo.title %></label>
    <%= form_for(todo, method: :delete, remote: true) do |f| %>
      <button type="submit" class="destroy"></button>
    <% end %>
  </div>
  <%= form_for(todo, remote: true, html: { "data-behavior" => "edit_todo_form" }) do |f| %>
    <%= f.text_field :title, class: "edit", "data-behavior" => "todo_title_input", "data-original-value" => todo.title %>
  <% end %>
</li>

app/views/todos/_toggle.js.erb
$("#<%= dom_id(todo) %>")
  .toggleClass("completed", <%= todo.completed? %>)
  .find("input.toggle")
  .prop("checked", <%= todo.completed? %>);

app/views/todos/create.js.erb
$("#todo-list").append("<%= j(render(@todo)) %>");

$("#new-todo").val("");

app/views/todos/destroy.js.erb
<%= render "destroy", todo: @todo %>

app/views/todos/destroy_completed.js.erb
<%= render partial: "destroy", collection: @todos_for_destruction, as: :todo %>

app/views/todos/index.html.erb
<%= link_to "Log out", destroy_user_session_path, :method => :delete %>
<section id="todoapp" class="<%= "has_todos" if @todos.all.count > 0 %>">


  <header id="header">
    <h1>todos</h1>
    <%= form_for(Todo.new, remote: true) do |f| %>
      <%= f.text_field :title, placeholder: "What needs to be done?", id: "new-todo", autofocus: true, "data-behavior" => "submit_on_enter" %>
    <% end %>
  </header>


  <section id="main">
    <%= form_tag(toggle_all_todos_path, method: :post, remote: true) do %>
      <input name="completed" id="toggle-all" type="checkbox" value="true" data-behavior="submit_on_check" <%= "checked" if @todos.count == 0 %>>
    <% end %>
    <ul id="todo-list">
      <%= render @todos.all %>
    </ul>
  </section>


  <%= render "footer" %>


</section>


<footer id="info">
  <p>Double-click to edit a todo</p>
  <p>Feedback on application to <a href="mailto:hd1+todo@jsc.d8u.us">Hasan</a>.</p>
</footer>

app/views/todos/toggle.js.erb
<%= render "toggle", todo: @todo %>

app/views/todos/toggle_all.js.erb
<%= render partial: "toggle", collection: @todos, as: :todo %>

app/views/todos/update.js.erb
$("#<%= dom_id(@todo) %>").replaceWith("<%= j(render(@todo)) %>");

app/views/welcome/index.html.erb
Track your tasks, like
a <a href="http://www.moleskine.com/">Moleskine</a> notebook, except
that you can <b>always read</b> what you wrote (which has been a problem
faced by <a href="http://www.prolificprogrammer.com">the author</a>
their whole life). Join us by <%= link_to 'signing in', '/users/sign_in'%>